### ISSUE TITLE
How to get Flight ID

### ISSUE THREAD

**Issue by hanbge** [willemo/flightstats#3]
Hello, I have a question about  [developer.flightstats.com/api-docs](developer.flightstats.com/api-docs)

There is a api: 
Get flight status by flight ID
[https://developer.flightstats.com/api-docs/flightstatus/v2/flight](https://developer.flightstats.com/api-docs/flightstatus/v2/flight)

But there is no algorithm by which you can guess or predict a Flight ID.

Please help me... tell me how to get Flight ID.

Thx

**Comment by willemo** [comment]
Hi, you can get the flight ID from the responses of the flight schedules and flight status endpoints. Questions about Flightstats' API should be directed to them, I only created this PHP client.
